# Generated by Django 5.1.4 on 2024-12-24 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todotask',
            options={},
        ),
        migrations.RemoveField(
            model_name='todotask',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='todotask',
            name='description',
        ),
        migrations.RemoveField(
            model_name='todotask',
            name='due_date',
        ),
        migrations.RemoveField(
            model_name='todotask',
            name='is_completed',
        ),
        migrations.RemoveField(
            model_name='todotask',
            name='updated_at',
        ),
    ]
